
stages:
  - lint
  - test

.xcode:
  tags:
    - xcode.12

.carthage:
  extends:
    - .xcode

lint:
  stage: lint
  script:
    - mkdir -p ./lint_output
    - swiftlint --config .swiftlint.yml > lint_output/lint.html
  cache: {}
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - lint_output/lint.html
  tags:
    - swiftlint


test:
  stage: test
  extends:
    - .carthage
  script:
    - bundle exec fastlane test
