stages:
  - prepare
  - lint
  - test

.xcode:
  tags:
    - xcode.12

.carthage:
  extends:
    - .xcode
  before_script:
    - bundle install
  cache:
    key: dmpods-cache-2
    paths:
      - Carthage/
    policy: pull

prepare:
  stage: prepare
  extends:
    - .carthage
  script:
    - ./conf.sh bootstrap --platform iOS --configuration Release --cache-builds --no-use-binaries
  cache:
    policy: pull-push

lint:
  stage: lint
  script:
    - mkdir -p ./lint_output
    - swiftlint --config .swiftlint.yml > lint_output/lint.html
  cache: {}
  needs: []
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - lint_output/lint.html
  tags:
    - swiftlint

test:ios:
  stage: test
  extends:
    - .carthage
  script:
    - bundle exec fastlane test
  needs:
    - job: prepare
      artifacts: false
    - job: lint
      artifacts: false

test:linux:
  stage: test
  tags:
    - docker
  image: swift:5.3
  cache: {}
  script:
    - swift test
  needs:
    - job: lint
      artifacts: false
