stages:
  - prepare
  - lint
  - test

prepare:
  stage: prepare
  script:
    - brew bundle
    - bundle install
    - carthage bootstrap --no-use-binaries --cache-builds --platform iOS
  tags:
    - ios
  cache:
    key: dmpods-cache
    paths:
      - Carthage/
    policy: pull-push

lint:
  stage: lint
  script:
    - mkdir -p ./lint_output
    - swiftlint --config .swiftlint.yml > lint_output/lint.html
  tags:
    - ios
  cache: {}
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - lint_output/lint.html


test:
  stage: test
  script:
    - bundle exec fastlane test
  tags:
    - ios
  cache:
    key: dmpods-cache
    paths:
      - Carthage/
    policy: pull
