
stages:
  - prepare
  - lint
  - test

.xcode:
  tags:
    - xcode.12.1

.carthage:
  extends:
    - .xcode
  before_script:
    - bundle install
  cache:
    key: dmpods-cache-12-1
    paths:
      - Carthage/
    policy: pull

prepare:
  stage: prepare
  extends:
    - .carthage
  script:
    - ./conf.sh bootstrap --no-use-binaries --cache-builds --platform iOS
  cache:
    policy: pull-push

lint:
  stage: lint
  script:
    - mkdir -p ./lint_output
    - swiftlint --config .swiftlint.yml > lint_output/lint.html
  cache: {}
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - lint_output/lint.html
  tags:
    - swiftlint


test:
  stage: test
  extends:
    - .carthage
  script:
    - bundle exec fastlane test
