
stages:
  - prepare
  - lint
  - test

.xcode:
  tags:
    - xcode.11.6

.carthage:
  extends:
    - .xcode
  before_script:
    - bundle install
  cache:
    key: dmpods-cache
    paths:
      - Carthage/
    policy: pull

prepare:
  stage: prepare
  extends:
    - .carthage
  script:
    - carthage bootstrap --no-use-binaries --cache-builds --platform iOS
  cache:
    policy: push

lint:
  stage: lint
  script:
    - mkdir -p ./lint_output
    - swiftlint --config .swiftlint.yml > lint_output/lint.html
  cache: {}
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - lint_output/lint.html


test:
  stage: test
  extends:
    - .carthage
  script:
    - bundle exec fastlane test
