default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    scan(
      workspace: "Example/DMTools.xcworkspace",
      scheme: "DMTools-Example",
    )
  end
end
